name: sec

on: [push, pull_request]

jobs:
    job1:
        runs-on: ubuntu-latest
        env:
            DB_URL: ${{ secrets.DB_URL }}
            DB_KEY: ${{ secrets.DB_KEY }}
        steps:
            run: echo "url: ${{ secrets.DB_URL }}"
            run: echo "key: ${{ secrets.DB_KEY }}"
